In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_wine

In [2]:
X, y = load_wine(return_X_y=True)

In [3]:
X.shape, y.shape

((178, 13), (178,))

In [4]:
X,y 

(array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.2, random_state=42)

In [7]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train, y_train)

y_pred_sk = lr.predict(X_test)

In [9]:
from sklearn.metrics import r2_score

r2_score_sk = r2_score(y_test, y_pred_sk)

r2_score_sk

0.8825140263270391

In [10]:
class Batch_Gradient_Descent():


    def __init__(self, learning_rate, epochs):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self, X_train, y_train):

        X_train = np.insert(X_train, 0, 1, axis=1)
        self.coef_ = np.random.randn(X_train.shape[1]) * 0.01
        self.intercept_ = 0

        for i in range(self.epochs):

            y_hat = np.dot(X_train, self.coef_) + self.intercept_
            intercept_slope = -2 * np.mean(y_train - y_hat)
            self.intercept_ = self.intercept_ + (self.lr * intercept_slope)

            coef_slope = -2 * np.mean(np.dot((y_train - y_hat), X_train))
            self.coef_ =  self.coef_ + (self.lr * coef_slope)

        print(f"Intercept_: {self.intercept_}, Coef_: {self.coef_}")
    
    def predict(self, X_test):

        X_test = np.insert(X_test, 0,1, axis=1)
        y_pred = self.intercept_ + np.dot(X_test, self.coef_)
        return y_pred

In [50]:
bgd = Batch_Gradient_Descent(learning_rate=0.0000000001, epochs=1000)

In [51]:
bgd.fit(X_train, y_train)

Intercept_: 4.428678573603258e-06, Coef_: [0.05296268 0.03104062 0.05162174 0.05031682 0.05011601 0.04603043
 0.04633395 0.03531028 0.04302569 0.04805264 0.04432369 0.0557774
 0.0514298  0.05731184]


In [52]:
y_pred = bgd.predict(X_test)

In [53]:
r2_score_c = r2_score(y_test, y_pred)
r2_score_c

-5323.64197957576

In [55]:
from sklearn.linear_model import SGDRegressor

sgd = SGDRegressor(learning_rate="constant", max_iter=100, eta0=0.0001)

sgd.fit(X_train, y_train)

y_pred_2 = sgd.predict(X_test)

In [56]:
r2_score(y_test, y_pred_2)

-6.536732349618864e+27

In [61]:
class Schostic_Gradient_Descent():

    def __init__(self, learning_rate, epochs):
        self.coef_ = None
        self.lr = learning_rate
        self.epochs = epochs
    
    def fit(self, X_train, y_train):

        X_train =  np.insert(X_train, 0,1, axis=1)
        self.coef_ = np.random.randn(X_train.shape[1]) * 0.01

        for i in range(self.epochs):

            for j in range(X_train.shape[0]):

                idx = np.random.randint(X_train.shape[0])
                y_hat = np.dot(X_train[idx], self.coef_)
                
                error = y_train[idx] - y_hat

                coef_slope = np.dot(error, X_train[idx])
                self.coef_ = self.coef_ + (self.lr * coef_slope)

        print(f"Coef: {self.coef_}")

    def predict(self, X_test):
        X_test = np.insert(X_test, 0, 1, axis=1)
        y_pred = np.dot(X_test, self.coef_)
        return y_pred

In [62]:
np.random.randint(X_train.shape[0])

130

In [63]:
np.random.randn(X_train.shape[1])

array([-0.02257097, -0.53949662,  0.45889827,  0.67826543,  0.34587843,
        1.04398987,  0.31568993, -0.26798533, -1.51344119,  0.70447556,
       -0.25062142, -0.00261209, -0.24219382])

In [64]:
sgd = Schostic_Gradient_Descent(learning_rate=0.000001, epochs=80)

In [65]:
sgd.fit(X_train, y_train)

Coef: [ 0.00988804  0.0123627  -0.00441509 -0.00560569  0.01256113  0.01601586
 -0.00707397 -0.00489295  0.01585326 -0.00446153  0.01998832  0.00538225
  0.00989601 -0.00130895]


In [66]:
y_pred_3 = sgd.predict(X_test)

In [67]:
r2_score(y_test, y_pred_3)

0.41211799072303446

In [203]:
class MiniBatch_Gradient_Descent():

    def __init__(self, batch_size, learning_rate, epochs):
        
        self.coef_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
    
    def fit(self, X_train, y_train):

        X_train = np.insert(X_test, 0, 1, axis=1)
        self.coef_ = np.random.randn(X_train.shape[1]) * 0.01

        for i in range(self.epochs):

            for j in range(int(X_train.shape[0] / self.batch_size)):

                idx = np.random.choice(X_train.shape[0], self.batch_size, replace=False)
                y_hat = np.dot(X_train[idx], self.coef_)
                
                error = y_train[idx] - y_hat
                coef_slope = -2 * np.dot(error, X_train[idx]) / self.batch_size
                self.coef_ = self.coef_ + (self.lr * coef_slope)

        print(f"Coef_: {self.coef_}")
    
    def predict(self, X_test):

        X_test = np.insert(X_test, 0, 1, axis=1)
        y_pred = np.dot(X_test, self.coef_)
        return y_pred

In [204]:
mgd = MiniBatch_Gradient_Descent(batch_size=128, learning_rate=0.0001, epochs=1000)

In [205]:
mgd.fit(X_train, y_train)

Coef_: [ 0.01549462 -0.00103688  0.01167473 -0.00721118  0.00368403  0.01428113
 -0.00361164  0.0057398   0.00617469 -0.00809935 -0.00511021  0.00386915
 -0.01966225  0.00802011]


In [206]:
y_pred_4 = mgd.predict(X_test)

In [207]:
r2_score(y_test, y_pred_4)

-101.96070136056134