In [1]:
import pandas as pd
import numpy as  np
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine

In [2]:
X, y = load_wine(return_X_y=True)

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
from sklearn.preprocessing import OneHotEncoder

one_hot = OneHotEncoder(sparse_output=False)

y_train = one_hot.fit_transform(y_train.reshape(-1, 1))

In [9]:
y_train

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0

In [17]:
def softmax(z):

    exp_value = np.exp(z - np.max(z, axis=1, keepdims=True))

    exp_value_sum = np.sum(exp_value, axis=1, keepdims=True)

    return exp_value / exp_value_sum

In [18]:
class Softmax_Regression():

    def __init__(self, learning_rate, epochs):

        self.coef_ = None
        self.lr = learning_rate
        self.epochs = epochs
    
    def fit(self, X_train, y_train):

        X_train = np.insert(X_train, 0, 1, axis=1)

        self.coef_ = np.random.randn(X_train.shape[1], y_train.shape[1]) * 0.01

        for i in range(self.epochs):

            y_hat = softmax(np.dot(X_train, self.coef_))

            coef_slope = np.dot(X_train.T, (y_hat - y_train)) / X_train.shape[0]

            self.coef_ = self.coef_ - (self.lr * coef_slope)

        print(f"Coef_slope: {self.coef_}")
    
    def predict(self, X_test):

        X_test = np.insert(X_test, 0, 1, axis=1)

        y_pred = np.argmax(softmax(np.dot(X_test, self.coef_)), axis=1)
        return y_pred

In [44]:
lg_softmax = Softmax_Regression(learning_rate=0.0001, epochs=1000)

In [45]:
lg_softmax.fit(X_train, y_train)

Coef_slope: [[-0.00153711  0.00994558 -0.00509683]
 [-0.0518514   0.0071567   0.03139567]
 [-0.00762098 -0.01293346  0.02411889]
 [-0.01560837  0.00302012  0.01601599]
 [-0.10695937  0.06796099  0.04842249]
 [-0.21928539  0.19156558  0.06514516]
 [ 0.01673952  0.01691714 -0.0215661 ]
 [ 0.00766044  0.01597582 -0.03106914]
 [ 0.00290895  0.01684931  0.02221673]
 [ 0.01827719  0.03889734 -0.01712456]
 [-0.03802543 -0.05399461  0.07314122]
 [-0.0214637   0.0043971  -0.00501496]
 [ 0.00433953  0.02066351 -0.0043285 ]
 [ 0.0456545  -0.01588206 -0.01902254]]


In [46]:
y_pred = lg_softmax.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score

acc_score = accuracy_score(y_test, y_pred)

acc_score

0.75